/* Copyright © 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */package cn.zhuatech.aieval.controller;import cn.zhuatech.aieval.common.ApiResponse;import cn.zhuatech.aieval.model.EvaluationAudit;import cn.zhuatech.aieval.service.AiEvaluationService;import jakarta.validation.Valid;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
@RestController@RequestMapping("/api/ai-eval")public class AiEvaluationController{private final AiEvaluationService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
public AiEvaluationController(AiEvaluationService s){service=s;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@PostMapping("/runs")@PreAuthorize("hasAnyRole('ADMIN','EVALUATOR')")public ApiResponse<AiEvaluationService.RunResult>run(@Valid@RequestBody AiEvaluationService.RunRequest r,Authentication a){return ApiResponse.ok("评测运行完成",service.run(r,a.getName()));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
@GetMapping("/audits")@PreAuthorize("hasAnyRole('ADMIN','AUDITOR')")public ApiResponse<List<EvaluationAudit>>audits(){return ApiResponse.ok("审计查询成功",service.audits());}}
